//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Blacklist struct {
	ID            *string `sql:"primary_key"`
	MappingID     string
	Service       string
	TrackID       string
	Reason        *string
	SkipCounter   int32
	LastSkippedAt *int32
	Created       int32
	Updated       int32
}
