//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Mappings struct {
	ID                  *string `sql:"primary_key"`
	SpotifyPlaylistID   string
	YoutubePlaylistID   string
	SpotifyPlaylistName *string
	YoutubePlaylistName *string
	SyncName            int32
	SyncTracks          int32
	IntervalMinutes     int32
	LastAnalysisAt      *int32
	TracksCount         int32
	Created             int32
	Updated             int32
}
