//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type OAuthTokens struct {
	ID           *string `sql:"primary_key"`
	Provider     string
	AccessToken  *string
	RefreshToken *string
	Expiry       *int32
	Scopes       *string
	Created      int32
	Updated      int32
}
