//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Settings struct {
	ID                  *string `sql:"primary_key"`
	SpotifyClientID     *string
	SpotifyClientSecret *string
	GoogleClientID      *string
	GoogleClientSecret  *string
	Created             int32
	Updated             int32
}
