//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type SyncItems struct {
	ID                  *string `sql:"primary_key"`
	MappingID           string
	Operation           string
	Service             string
	TrackID             *string
	TrackTitle          *string
	TrackArtist         *string
	Status              string
	ErrorMessage        *string
	AttemptCount        int32
	LastAttemptAt       *int32
	Created             int32
	Updated             int32
	AnalysisContextJSON *string
}
