/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SetupLazyImport = createFileRoute('/setup')()
const LogsLazyImport = createFileRoute('/logs')()
const DashboardLazyImport = createFileRoute('/dashboard')()
const IndexLazyImport = createFileRoute('/')()
const SetupIndexLazyImport = createFileRoute('/setup/')()
const MappingsIndexLazyImport = createFileRoute('/mappings/')()
const SetupSuccessLazyImport = createFileRoute('/setup/success')()
const SettingsYoutubeLazyImport = createFileRoute('/settings/youtube')()
const SettingsSpotifyLazyImport = createFileRoute('/settings/spotify')()
const MappingsNewLazyImport = createFileRoute('/mappings/new')()
const MappingsMappingIdEditLazyImport = createFileRoute(
  '/mappings/$mappingId/edit',
)()
const MappingsMappingIdBlacklistLazyImport = createFileRoute(
  '/mappings/$mappingId/blacklist',
)()

// Create/Update Routes

const SetupLazyRoute = SetupLazyImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/setup.lazy').then((d) => d.Route))

const LogsLazyRoute = LogsLazyImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logs.lazy').then((d) => d.Route))

const DashboardLazyRoute = DashboardLazyImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SetupIndexLazyRoute = SetupIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupLazyRoute,
} as any).lazy(() => import('./routes/setup/index.lazy').then((d) => d.Route))

const MappingsIndexLazyRoute = MappingsIndexLazyImport.update({
  id: '/mappings/',
  path: '/mappings/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/mappings/index.lazy').then((d) => d.Route),
)

const SetupSuccessLazyRoute = SetupSuccessLazyImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SetupLazyRoute,
} as any).lazy(() => import('./routes/setup/success.lazy').then((d) => d.Route))

const SettingsYoutubeLazyRoute = SettingsYoutubeLazyImport.update({
  id: '/settings/youtube',
  path: '/settings/youtube',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/settings/youtube.lazy').then((d) => d.Route),
)

const SettingsSpotifyLazyRoute = SettingsSpotifyLazyImport.update({
  id: '/settings/spotify',
  path: '/settings/spotify',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/settings/spotify.lazy').then((d) => d.Route),
)

const MappingsNewLazyRoute = MappingsNewLazyImport.update({
  id: '/mappings/new',
  path: '/mappings/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mappings/new.lazy').then((d) => d.Route))

const MappingsMappingIdEditLazyRoute = MappingsMappingIdEditLazyImport.update({
  id: '/mappings/$mappingId/edit',
  path: '/mappings/$mappingId/edit',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/mappings/$mappingId/edit.lazy').then((d) => d.Route),
)

const MappingsMappingIdBlacklistLazyRoute =
  MappingsMappingIdBlacklistLazyImport.update({
    id: '/mappings/$mappingId/blacklist',
    path: '/mappings/$mappingId/blacklist',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/mappings/$mappingId/blacklist.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsLazyImport
      parentRoute: typeof rootRoute
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupLazyImport
      parentRoute: typeof rootRoute
    }
    '/mappings/new': {
      id: '/mappings/new'
      path: '/mappings/new'
      fullPath: '/mappings/new'
      preLoaderRoute: typeof MappingsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/spotify': {
      id: '/settings/spotify'
      path: '/settings/spotify'
      fullPath: '/settings/spotify'
      preLoaderRoute: typeof SettingsSpotifyLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/youtube': {
      id: '/settings/youtube'
      path: '/settings/youtube'
      fullPath: '/settings/youtube'
      preLoaderRoute: typeof SettingsYoutubeLazyImport
      parentRoute: typeof rootRoute
    }
    '/setup/success': {
      id: '/setup/success'
      path: '/success'
      fullPath: '/setup/success'
      preLoaderRoute: typeof SetupSuccessLazyImport
      parentRoute: typeof SetupLazyImport
    }
    '/mappings/': {
      id: '/mappings/'
      path: '/mappings'
      fullPath: '/mappings'
      preLoaderRoute: typeof MappingsIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexLazyImport
      parentRoute: typeof SetupLazyImport
    }
    '/mappings/$mappingId/blacklist': {
      id: '/mappings/$mappingId/blacklist'
      path: '/mappings/$mappingId/blacklist'
      fullPath: '/mappings/$mappingId/blacklist'
      preLoaderRoute: typeof MappingsMappingIdBlacklistLazyImport
      parentRoute: typeof rootRoute
    }
    '/mappings/$mappingId/edit': {
      id: '/mappings/$mappingId/edit'
      path: '/mappings/$mappingId/edit'
      fullPath: '/mappings/$mappingId/edit'
      preLoaderRoute: typeof MappingsMappingIdEditLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface SetupLazyRouteChildren {
  SetupSuccessLazyRoute: typeof SetupSuccessLazyRoute
  SetupIndexLazyRoute: typeof SetupIndexLazyRoute
}

const SetupLazyRouteChildren: SetupLazyRouteChildren = {
  SetupSuccessLazyRoute: SetupSuccessLazyRoute,
  SetupIndexLazyRoute: SetupIndexLazyRoute,
}

const SetupLazyRouteWithChildren = SetupLazyRoute._addFileChildren(
  SetupLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/logs': typeof LogsLazyRoute
  '/setup': typeof SetupLazyRouteWithChildren
  '/mappings/new': typeof MappingsNewLazyRoute
  '/settings/spotify': typeof SettingsSpotifyLazyRoute
  '/settings/youtube': typeof SettingsYoutubeLazyRoute
  '/setup/success': typeof SetupSuccessLazyRoute
  '/mappings': typeof MappingsIndexLazyRoute
  '/setup/': typeof SetupIndexLazyRoute
  '/mappings/$mappingId/blacklist': typeof MappingsMappingIdBlacklistLazyRoute
  '/mappings/$mappingId/edit': typeof MappingsMappingIdEditLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/logs': typeof LogsLazyRoute
  '/mappings/new': typeof MappingsNewLazyRoute
  '/settings/spotify': typeof SettingsSpotifyLazyRoute
  '/settings/youtube': typeof SettingsYoutubeLazyRoute
  '/setup/success': typeof SetupSuccessLazyRoute
  '/mappings': typeof MappingsIndexLazyRoute
  '/setup': typeof SetupIndexLazyRoute
  '/mappings/$mappingId/blacklist': typeof MappingsMappingIdBlacklistLazyRoute
  '/mappings/$mappingId/edit': typeof MappingsMappingIdEditLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLazyRoute
  '/logs': typeof LogsLazyRoute
  '/setup': typeof SetupLazyRouteWithChildren
  '/mappings/new': typeof MappingsNewLazyRoute
  '/settings/spotify': typeof SettingsSpotifyLazyRoute
  '/settings/youtube': typeof SettingsYoutubeLazyRoute
  '/setup/success': typeof SetupSuccessLazyRoute
  '/mappings/': typeof MappingsIndexLazyRoute
  '/setup/': typeof SetupIndexLazyRoute
  '/mappings/$mappingId/blacklist': typeof MappingsMappingIdBlacklistLazyRoute
  '/mappings/$mappingId/edit': typeof MappingsMappingIdEditLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/logs'
    | '/setup'
    | '/mappings/new'
    | '/settings/spotify'
    | '/settings/youtube'
    | '/setup/success'
    | '/mappings'
    | '/setup/'
    | '/mappings/$mappingId/blacklist'
    | '/mappings/$mappingId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/logs'
    | '/mappings/new'
    | '/settings/spotify'
    | '/settings/youtube'
    | '/setup/success'
    | '/mappings'
    | '/setup'
    | '/mappings/$mappingId/blacklist'
    | '/mappings/$mappingId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/logs'
    | '/setup'
    | '/mappings/new'
    | '/settings/spotify'
    | '/settings/youtube'
    | '/setup/success'
    | '/mappings/'
    | '/setup/'
    | '/mappings/$mappingId/blacklist'
    | '/mappings/$mappingId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardLazyRoute: typeof DashboardLazyRoute
  LogsLazyRoute: typeof LogsLazyRoute
  SetupLazyRoute: typeof SetupLazyRouteWithChildren
  MappingsNewLazyRoute: typeof MappingsNewLazyRoute
  SettingsSpotifyLazyRoute: typeof SettingsSpotifyLazyRoute
  SettingsYoutubeLazyRoute: typeof SettingsYoutubeLazyRoute
  MappingsIndexLazyRoute: typeof MappingsIndexLazyRoute
  MappingsMappingIdBlacklistLazyRoute: typeof MappingsMappingIdBlacklistLazyRoute
  MappingsMappingIdEditLazyRoute: typeof MappingsMappingIdEditLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardLazyRoute: DashboardLazyRoute,
  LogsLazyRoute: LogsLazyRoute,
  SetupLazyRoute: SetupLazyRouteWithChildren,
  MappingsNewLazyRoute: MappingsNewLazyRoute,
  SettingsSpotifyLazyRoute: SettingsSpotifyLazyRoute,
  SettingsYoutubeLazyRoute: SettingsYoutubeLazyRoute,
  MappingsIndexLazyRoute: MappingsIndexLazyRoute,
  MappingsMappingIdBlacklistLazyRoute: MappingsMappingIdBlacklistLazyRoute,
  MappingsMappingIdEditLazyRoute: MappingsMappingIdEditLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/logs",
        "/setup",
        "/mappings/new",
        "/settings/spotify",
        "/settings/youtube",
        "/mappings/",
        "/mappings/$mappingId/blacklist",
        "/mappings/$mappingId/edit"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.lazy.tsx"
    },
    "/logs": {
      "filePath": "logs.lazy.tsx"
    },
    "/setup": {
      "filePath": "setup.lazy.tsx",
      "children": [
        "/setup/success",
        "/setup/"
      ]
    },
    "/mappings/new": {
      "filePath": "mappings/new.lazy.tsx"
    },
    "/settings/spotify": {
      "filePath": "settings/spotify.lazy.tsx"
    },
    "/settings/youtube": {
      "filePath": "settings/youtube.lazy.tsx"
    },
    "/setup/success": {
      "filePath": "setup/success.lazy.tsx",
      "parent": "/setup"
    },
    "/mappings/": {
      "filePath": "mappings/index.lazy.tsx"
    },
    "/setup/": {
      "filePath": "setup/index.lazy.tsx",
      "parent": "/setup"
    },
    "/mappings/$mappingId/blacklist": {
      "filePath": "mappings/$mappingId/blacklist.lazy.tsx"
    },
    "/mappings/$mappingId/edit": {
      "filePath": "mappings/$mappingId/edit.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
