//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var ActivityLogs = newActivityLogsTable("", "activity_logs", "")

type activityLogsTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnString
	Level     sqlite.ColumnString
	Message   sqlite.ColumnString
	MappingID sqlite.ColumnString
	JobType   sqlite.ColumnString
	Created   sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ActivityLogsTable struct {
	activityLogsTable

	EXCLUDED activityLogsTable
}

// AS creates new ActivityLogsTable with assigned alias
func (a ActivityLogsTable) AS(alias string) *ActivityLogsTable {
	return newActivityLogsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ActivityLogsTable with assigned schema name
func (a ActivityLogsTable) FromSchema(schemaName string) *ActivityLogsTable {
	return newActivityLogsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ActivityLogsTable with assigned table prefix
func (a ActivityLogsTable) WithPrefix(prefix string) *ActivityLogsTable {
	return newActivityLogsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ActivityLogsTable with assigned table suffix
func (a ActivityLogsTable) WithSuffix(suffix string) *ActivityLogsTable {
	return newActivityLogsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newActivityLogsTable(schemaName, tableName, alias string) *ActivityLogsTable {
	return &ActivityLogsTable{
		activityLogsTable: newActivityLogsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newActivityLogsTableImpl("", "excluded", ""),
	}
}

func newActivityLogsTableImpl(schemaName, tableName, alias string) activityLogsTable {
	var (
		IDColumn        = sqlite.StringColumn("id")
		LevelColumn     = sqlite.StringColumn("level")
		MessageColumn   = sqlite.StringColumn("message")
		MappingIDColumn = sqlite.StringColumn("mapping_id")
		JobTypeColumn   = sqlite.StringColumn("job_type")
		CreatedColumn   = sqlite.IntegerColumn("created")
		allColumns      = sqlite.ColumnList{IDColumn, LevelColumn, MessageColumn, MappingIDColumn, JobTypeColumn, CreatedColumn}
		mutableColumns  = sqlite.ColumnList{LevelColumn, MessageColumn, MappingIDColumn, JobTypeColumn, CreatedColumn}
		defaultColumns  = sqlite.ColumnList{}
	)

	return activityLogsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Level:     LevelColumn,
		Message:   MessageColumn,
		MappingID: MappingIDColumn,
		JobType:   JobTypeColumn,
		Created:   CreatedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
