//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Blacklist = newBlacklistTable("", "blacklist", "")

type blacklistTable struct {
	sqlite.Table

	// Columns
	ID            sqlite.ColumnString
	MappingID     sqlite.ColumnString
	Service       sqlite.ColumnString
	TrackID       sqlite.ColumnString
	Reason        sqlite.ColumnString
	SkipCounter   sqlite.ColumnInteger
	LastSkippedAt sqlite.ColumnInteger
	Created       sqlite.ColumnInteger
	Updated       sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type BlacklistTable struct {
	blacklistTable

	EXCLUDED blacklistTable
}

// AS creates new BlacklistTable with assigned alias
func (a BlacklistTable) AS(alias string) *BlacklistTable {
	return newBlacklistTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BlacklistTable with assigned schema name
func (a BlacklistTable) FromSchema(schemaName string) *BlacklistTable {
	return newBlacklistTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BlacklistTable with assigned table prefix
func (a BlacklistTable) WithPrefix(prefix string) *BlacklistTable {
	return newBlacklistTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BlacklistTable with assigned table suffix
func (a BlacklistTable) WithSuffix(suffix string) *BlacklistTable {
	return newBlacklistTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBlacklistTable(schemaName, tableName, alias string) *BlacklistTable {
	return &BlacklistTable{
		blacklistTable: newBlacklistTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newBlacklistTableImpl("", "excluded", ""),
	}
}

func newBlacklistTableImpl(schemaName, tableName, alias string) blacklistTable {
	var (
		IDColumn            = sqlite.StringColumn("id")
		MappingIDColumn     = sqlite.StringColumn("mapping_id")
		ServiceColumn       = sqlite.StringColumn("service")
		TrackIDColumn       = sqlite.StringColumn("track_id")
		ReasonColumn        = sqlite.StringColumn("reason")
		SkipCounterColumn   = sqlite.IntegerColumn("skip_counter")
		LastSkippedAtColumn = sqlite.IntegerColumn("last_skipped_at")
		CreatedColumn       = sqlite.IntegerColumn("created")
		UpdatedColumn       = sqlite.IntegerColumn("updated")
		allColumns          = sqlite.ColumnList{IDColumn, MappingIDColumn, ServiceColumn, TrackIDColumn, ReasonColumn, SkipCounterColumn, LastSkippedAtColumn, CreatedColumn, UpdatedColumn}
		mutableColumns      = sqlite.ColumnList{MappingIDColumn, ServiceColumn, TrackIDColumn, ReasonColumn, SkipCounterColumn, LastSkippedAtColumn, CreatedColumn, UpdatedColumn}
		defaultColumns      = sqlite.ColumnList{SkipCounterColumn}
	)

	return blacklistTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		MappingID:     MappingIDColumn,
		Service:       ServiceColumn,
		TrackID:       TrackIDColumn,
		Reason:        ReasonColumn,
		SkipCounter:   SkipCounterColumn,
		LastSkippedAt: LastSkippedAtColumn,
		Created:       CreatedColumn,
		Updated:       UpdatedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
