//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Mappings = newMappingsTable("", "mappings", "")

type mappingsTable struct {
	sqlite.Table

	// Columns
	ID                  sqlite.ColumnString
	SpotifyPlaylistID   sqlite.ColumnString
	YoutubePlaylistID   sqlite.ColumnString
	SpotifyPlaylistName sqlite.ColumnString
	YoutubePlaylistName sqlite.ColumnString
	SyncName            sqlite.ColumnInteger
	SyncTracks          sqlite.ColumnInteger
	IntervalMinutes     sqlite.ColumnInteger
	LastAnalysisAt      sqlite.ColumnInteger
	TracksCount         sqlite.ColumnInteger
	Created             sqlite.ColumnInteger
	Updated             sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type MappingsTable struct {
	mappingsTable

	EXCLUDED mappingsTable
}

// AS creates new MappingsTable with assigned alias
func (a MappingsTable) AS(alias string) *MappingsTable {
	return newMappingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MappingsTable with assigned schema name
func (a MappingsTable) FromSchema(schemaName string) *MappingsTable {
	return newMappingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MappingsTable with assigned table prefix
func (a MappingsTable) WithPrefix(prefix string) *MappingsTable {
	return newMappingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MappingsTable with assigned table suffix
func (a MappingsTable) WithSuffix(suffix string) *MappingsTable {
	return newMappingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMappingsTable(schemaName, tableName, alias string) *MappingsTable {
	return &MappingsTable{
		mappingsTable: newMappingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newMappingsTableImpl("", "excluded", ""),
	}
}

func newMappingsTableImpl(schemaName, tableName, alias string) mappingsTable {
	var (
		IDColumn                  = sqlite.StringColumn("id")
		SpotifyPlaylistIDColumn   = sqlite.StringColumn("spotify_playlist_id")
		YoutubePlaylistIDColumn   = sqlite.StringColumn("youtube_playlist_id")
		SpotifyPlaylistNameColumn = sqlite.StringColumn("spotify_playlist_name")
		YoutubePlaylistNameColumn = sqlite.StringColumn("youtube_playlist_name")
		SyncNameColumn            = sqlite.IntegerColumn("sync_name")
		SyncTracksColumn          = sqlite.IntegerColumn("sync_tracks")
		IntervalMinutesColumn     = sqlite.IntegerColumn("interval_minutes")
		LastAnalysisAtColumn      = sqlite.IntegerColumn("last_analysis_at")
		TracksCountColumn         = sqlite.IntegerColumn("tracks_count")
		CreatedColumn             = sqlite.IntegerColumn("created")
		UpdatedColumn             = sqlite.IntegerColumn("updated")
		allColumns                = sqlite.ColumnList{IDColumn, SpotifyPlaylistIDColumn, YoutubePlaylistIDColumn, SpotifyPlaylistNameColumn, YoutubePlaylistNameColumn, SyncNameColumn, SyncTracksColumn, IntervalMinutesColumn, LastAnalysisAtColumn, TracksCountColumn, CreatedColumn, UpdatedColumn}
		mutableColumns            = sqlite.ColumnList{SpotifyPlaylistIDColumn, YoutubePlaylistIDColumn, SpotifyPlaylistNameColumn, YoutubePlaylistNameColumn, SyncNameColumn, SyncTracksColumn, IntervalMinutesColumn, LastAnalysisAtColumn, TracksCountColumn, CreatedColumn, UpdatedColumn}
		defaultColumns            = sqlite.ColumnList{SyncNameColumn, SyncTracksColumn, IntervalMinutesColumn, TracksCountColumn}
	)

	return mappingsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		SpotifyPlaylistID:   SpotifyPlaylistIDColumn,
		YoutubePlaylistID:   YoutubePlaylistIDColumn,
		SpotifyPlaylistName: SpotifyPlaylistNameColumn,
		YoutubePlaylistName: YoutubePlaylistNameColumn,
		SyncName:            SyncNameColumn,
		SyncTracks:          SyncTracksColumn,
		IntervalMinutes:     IntervalMinutesColumn,
		LastAnalysisAt:      LastAnalysisAtColumn,
		TracksCount:         TracksCountColumn,
		Created:             CreatedColumn,
		Updated:             UpdatedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
