//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var OAuthTokens = newOAuthTokensTable("", "oauth_tokens", "")

type oAuthTokensTable struct {
	sqlite.Table

	// Columns
	ID           sqlite.ColumnString
	Provider     sqlite.ColumnString
	AccessToken  sqlite.ColumnString
	RefreshToken sqlite.ColumnString
	Expiry       sqlite.ColumnInteger
	Scopes       sqlite.ColumnString
	Created      sqlite.ColumnInteger
	Updated      sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type OAuthTokensTable struct {
	oAuthTokensTable

	EXCLUDED oAuthTokensTable
}

// AS creates new OAuthTokensTable with assigned alias
func (a OAuthTokensTable) AS(alias string) *OAuthTokensTable {
	return newOAuthTokensTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OAuthTokensTable with assigned schema name
func (a OAuthTokensTable) FromSchema(schemaName string) *OAuthTokensTable {
	return newOAuthTokensTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OAuthTokensTable with assigned table prefix
func (a OAuthTokensTable) WithPrefix(prefix string) *OAuthTokensTable {
	return newOAuthTokensTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OAuthTokensTable with assigned table suffix
func (a OAuthTokensTable) WithSuffix(suffix string) *OAuthTokensTable {
	return newOAuthTokensTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOAuthTokensTable(schemaName, tableName, alias string) *OAuthTokensTable {
	return &OAuthTokensTable{
		oAuthTokensTable: newOAuthTokensTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newOAuthTokensTableImpl("", "excluded", ""),
	}
}

func newOAuthTokensTableImpl(schemaName, tableName, alias string) oAuthTokensTable {
	var (
		IDColumn           = sqlite.StringColumn("id")
		ProviderColumn     = sqlite.StringColumn("provider")
		AccessTokenColumn  = sqlite.StringColumn("access_token")
		RefreshTokenColumn = sqlite.StringColumn("refresh_token")
		ExpiryColumn       = sqlite.IntegerColumn("expiry")
		ScopesColumn       = sqlite.StringColumn("scopes")
		CreatedColumn      = sqlite.IntegerColumn("created")
		UpdatedColumn      = sqlite.IntegerColumn("updated")
		allColumns         = sqlite.ColumnList{IDColumn, ProviderColumn, AccessTokenColumn, RefreshTokenColumn, ExpiryColumn, ScopesColumn, CreatedColumn, UpdatedColumn}
		mutableColumns     = sqlite.ColumnList{ProviderColumn, AccessTokenColumn, RefreshTokenColumn, ExpiryColumn, ScopesColumn, CreatedColumn, UpdatedColumn}
		defaultColumns     = sqlite.ColumnList{}
	)

	return oAuthTokensTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Provider:     ProviderColumn,
		AccessToken:  AccessTokenColumn,
		RefreshToken: RefreshTokenColumn,
		Expiry:       ExpiryColumn,
		Scopes:       ScopesColumn,
		Created:      CreatedColumn,
		Updated:      UpdatedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
