//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Settings = newSettingsTable("", "settings", "")

type settingsTable struct {
	sqlite.Table

	// Columns
	ID                  sqlite.ColumnString
	SpotifyClientID     sqlite.ColumnString
	SpotifyClientSecret sqlite.ColumnString
	GoogleClientID      sqlite.ColumnString
	GoogleClientSecret  sqlite.ColumnString
	Created             sqlite.ColumnInteger
	Updated             sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type SettingsTable struct {
	settingsTable

	EXCLUDED settingsTable
}

// AS creates new SettingsTable with assigned alias
func (a SettingsTable) AS(alias string) *SettingsTable {
	return newSettingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SettingsTable with assigned schema name
func (a SettingsTable) FromSchema(schemaName string) *SettingsTable {
	return newSettingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SettingsTable with assigned table prefix
func (a SettingsTable) WithPrefix(prefix string) *SettingsTable {
	return newSettingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SettingsTable with assigned table suffix
func (a SettingsTable) WithSuffix(suffix string) *SettingsTable {
	return newSettingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSettingsTable(schemaName, tableName, alias string) *SettingsTable {
	return &SettingsTable{
		settingsTable: newSettingsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newSettingsTableImpl("", "excluded", ""),
	}
}

func newSettingsTableImpl(schemaName, tableName, alias string) settingsTable {
	var (
		IDColumn                  = sqlite.StringColumn("id")
		SpotifyClientIDColumn     = sqlite.StringColumn("spotify_client_id")
		SpotifyClientSecretColumn = sqlite.StringColumn("spotify_client_secret")
		GoogleClientIDColumn      = sqlite.StringColumn("google_client_id")
		GoogleClientSecretColumn  = sqlite.StringColumn("google_client_secret")
		CreatedColumn             = sqlite.IntegerColumn("created")
		UpdatedColumn             = sqlite.IntegerColumn("updated")
		allColumns                = sqlite.ColumnList{IDColumn, SpotifyClientIDColumn, SpotifyClientSecretColumn, GoogleClientIDColumn, GoogleClientSecretColumn, CreatedColumn, UpdatedColumn}
		mutableColumns            = sqlite.ColumnList{SpotifyClientIDColumn, SpotifyClientSecretColumn, GoogleClientIDColumn, GoogleClientSecretColumn, CreatedColumn, UpdatedColumn}
		defaultColumns            = sqlite.ColumnList{IDColumn}
	)

	return settingsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		SpotifyClientID:     SpotifyClientIDColumn,
		SpotifyClientSecret: SpotifyClientSecretColumn,
		GoogleClientID:      GoogleClientIDColumn,
		GoogleClientSecret:  GoogleClientSecretColumn,
		Created:             CreatedColumn,
		Updated:             UpdatedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
