//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var SyncItems = newSyncItemsTable("", "sync_items", "")

type syncItemsTable struct {
	sqlite.Table

	// Columns
	ID            sqlite.ColumnString
	MappingID     sqlite.ColumnString
	Operation     sqlite.ColumnString
	Service       sqlite.ColumnString
	TrackID       sqlite.ColumnString
	TrackTitle    sqlite.ColumnString
	TrackArtist   sqlite.ColumnString
	Status        sqlite.ColumnString
	ErrorMessage  sqlite.ColumnString
	AttemptCount  sqlite.ColumnInteger
	LastAttemptAt sqlite.ColumnInteger
	Created       sqlite.ColumnInteger
	Updated       sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type SyncItemsTable struct {
	syncItemsTable

	EXCLUDED syncItemsTable
}

// AS creates new SyncItemsTable with assigned alias
func (a SyncItemsTable) AS(alias string) *SyncItemsTable {
	return newSyncItemsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SyncItemsTable with assigned schema name
func (a SyncItemsTable) FromSchema(schemaName string) *SyncItemsTable {
	return newSyncItemsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SyncItemsTable with assigned table prefix
func (a SyncItemsTable) WithPrefix(prefix string) *SyncItemsTable {
	return newSyncItemsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SyncItemsTable with assigned table suffix
func (a SyncItemsTable) WithSuffix(suffix string) *SyncItemsTable {
	return newSyncItemsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSyncItemsTable(schemaName, tableName, alias string) *SyncItemsTable {
	return &SyncItemsTable{
		syncItemsTable: newSyncItemsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newSyncItemsTableImpl("", "excluded", ""),
	}
}

func newSyncItemsTableImpl(schemaName, tableName, alias string) syncItemsTable {
	var (
		IDColumn            = sqlite.StringColumn("id")
		MappingIDColumn     = sqlite.StringColumn("mapping_id")
		OperationColumn     = sqlite.StringColumn("operation")
		ServiceColumn       = sqlite.StringColumn("service")
		TrackIDColumn       = sqlite.StringColumn("track_id")
		TrackTitleColumn    = sqlite.StringColumn("track_title")
		TrackArtistColumn   = sqlite.StringColumn("track_artist")
		StatusColumn        = sqlite.StringColumn("status")
		ErrorMessageColumn  = sqlite.StringColumn("error_message")
		AttemptCountColumn  = sqlite.IntegerColumn("attempt_count")
		LastAttemptAtColumn = sqlite.IntegerColumn("last_attempt_at")
		CreatedColumn       = sqlite.IntegerColumn("created")
		UpdatedColumn       = sqlite.IntegerColumn("updated")
		allColumns          = sqlite.ColumnList{IDColumn, MappingIDColumn, OperationColumn, ServiceColumn, TrackIDColumn, TrackTitleColumn, TrackArtistColumn, StatusColumn, ErrorMessageColumn, AttemptCountColumn, LastAttemptAtColumn, CreatedColumn, UpdatedColumn}
		mutableColumns      = sqlite.ColumnList{MappingIDColumn, OperationColumn, ServiceColumn, TrackIDColumn, TrackTitleColumn, TrackArtistColumn, StatusColumn, ErrorMessageColumn, AttemptCountColumn, LastAttemptAtColumn, CreatedColumn, UpdatedColumn}
		defaultColumns      = sqlite.ColumnList{StatusColumn, AttemptCountColumn}
	)

	return syncItemsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		MappingID:     MappingIDColumn,
		Operation:     OperationColumn,
		Service:       ServiceColumn,
		TrackID:       TrackIDColumn,
		TrackTitle:    TrackTitleColumn,
		TrackArtist:   TrackArtistColumn,
		Status:        StatusColumn,
		ErrorMessage:  ErrorMessageColumn,
		AttemptCount:  AttemptCountColumn,
		LastAttemptAt: LastAttemptAtColumn,
		Created:       CreatedColumn,
		Updated:       UpdatedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
